### ISSUE TITLE
Add a "contributing" section

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/cneuromod.ca#13]
## Context

currently, when surfing on the [neuromod website](https://www.cneuromod.ca/) (which is beautiful BTW), there is no clear indications for how to contribute to the project (codewise), for internal and external contributors.

## Suggestion

Add a redirection to a CONTRIBUTING page.

**Comment by lunebellec** [comment]
That's a great point. 

As cneuromod transitions towards a more open, community-driven project organization, it would be important to help people understand how they can get involved. As usual, there should be some detailed information on https://docs.cneuromod.ca and an overview on https://cneuromod.ca

**Comment by lunebellec** [comment]
See https://docs.cneuromod.ca/en/latest/COC.html
