### ISSUE TITLE
youtube links

### ISSUE THREAD

**Issue by lunebellec** [courtois-neuromod/cneuromod.ca#14]
@julieaboyle1 @vborghe is it ok if I add the youtube links to the cneuromonth 2021 blog post, or would you rather have a separate post?

**Comment by vborghe** [comment]
Originally, we though we'd ask @FrancoisPgm to write a super short blogpost (literally just _"we did this thing, I did most of it, I survived, and here are the links to the talks!"_) which would kill a lot of birds with one stone (keep the blog updated while diversifying its authors, share the links, highlight the huge work of Francois, etc..). Of course I don't want to add too much on Francois' plate nor pressure him! Just a thought.

**Comment by julieaboyle1** [comment]
Just asking Francois P now... :-)

**Comment by FrancoisPgm** [comment]
I wrote the blogpost but I don't have the permission to push.

**Comment by lunebellec** [comment]
@FrancoisPgm your are now a maintainer of the repo!

Please open a PR for review.
